import Link from "next/link";
import { Accordion } from "@/components/navigation";
import { DealerHeader, DealerShell, wholesaleFaq, wholesaleProducts } from "@/features/b2b";
import styles from "@/features/b2b/B2B.module.css";
export function DealerDashboard() { const cards=[["Dealer status","Verification not connected"],["Recent quotations","No live quotations"],["Recent orders","No live dealer orders"],["Quick actions","Catalogue, quotation and support previews"]]; return <DealerShell><DealerHeader eyebrow="Private portal preview" title="Dealer dashboard" description="A synthetic B2B workspace without authentication, dealer records or commercial data." /><div className={styles.grid}>{cards.map(([title,body])=><article className={styles.card} key={title}><h2>{title}</h2><span className={styles.badge}>Placeholder</span><p>{body}</p></article>)}</div></DealerShell>; }
export function DealerCatalogue() { return <DealerShell><DealerHeader eyebrow="Dealer catalogue shell" title="Wholesale catalogue" description="Dealer-only presentation banner without access control or real wholesale pricing." /><p className={styles.privateBanner}>Visibility placeholder: future approved dealer accounts only. This static route contains no confidential data.</p><div className={styles.grid}>{wholesaleProducts.map((name)=><article className={styles.card} key={name}><div aria-label={`Reserved media for ${name}`} className={styles.heroMedia} role="img">SS</div><h2>{name}</h2><p>Wholesale price available only through an approved future quotation.</p><button className={styles.button} type="button">Add to quotation preview</button></article>)}</div></DealerShell>; }
export function DealerPricing() { return <DealerShell><DealerHeader eyebrow="Commercial terms preview" title="Pricing and credit terms" description="Explanatory placeholders only; no price, discount, credit limit or approval is exposed." /><div className={styles.twoGrid}><article className={styles.card}><h2>Volume pricing</h2><p>Future quotations may reflect approved quantity and product context. No tier or discount is promised.</p></article><article className={styles.card}><h2>MOQ</h2><p>Minimum quantities remain quotation-specific and pending policy.</p></article><article className={styles.card}><h2>Payment terms</h2><p>Payment timing and methods require separate approval.</p></article><article className={styles.card}><h2>Credit terms</h2><p>No credit facility, limit or eligibility is represented.</p></article></div></DealerShell>; }
export function DealerKyc() { const items=["GST document placeholder","Business license placeholder","Identity placeholder","Bank details placeholder"]; return <DealerShell><DealerHeader eyebrow="Verification UI" title="Business verification" description="No upload, document, bank information or KYC verification is processed." /><div className={styles.grid}>{items.map((item)=><article className={styles.card} key={item}><h2>{item}</h2><span className={styles.badge}>Not submitted</span><input aria-label={item} disabled type="file" /><button className={styles.button} disabled type="button">Upload unavailable</button></article>)}</div></DealerShell>; }
export function DealerOrders() { return <DealerShell><DealerHeader eyebrow="Trade order history shell" title="Dealer orders" description="No live orders, invoices, shipments or tracking data." /><article className={styles.card}><h2>Synthetic order preview</h2><span className={styles.badge}>Not a live order</span><p>Invoice unavailable · Tracking unavailable · Total unavailable</p><div className={styles.actions}><button className={styles.button} type="button">Invoice placeholder</button><button className={styles.button} type="button">Track placeholder</button></div></article><div className={styles.empty} role="status"><h2>No dealer orders</h2><p>Authenticated trade history requires a future service.</p></div></DealerShell>; }
export function DealerDownloads() { const items=["Trade catalogue placeholder","Price list placeholder","Brand assets placeholder","Marketing kit placeholder"]; return <DealerShell><DealerHeader eyebrow="Resource library shell" title="Downloads" description="No business data or downloadable file is exposed." /><div className={styles.grid}>{items.map((item)=><article className={styles.card} key={item}><h2>{item}</h2><p>Reserved for a future approved, access-controlled asset.</p><button className={styles.button} type="button">Download unavailable</button></article>)}</div></DealerShell>; }
export function DealerSupport() { return <DealerShell><DealerHeader eyebrow="Dealer care preview" title="Wholesale support" description="Account-manager and support channels are placeholders without assigned personnel." /><div className={styles.grid}><article className={styles.card}><h2>Account manager</h2><p>Not assigned</p></article><article className={styles.card}><h2>WhatsApp</h2><Link className={styles.button} href="/whatsapp">Open contact placeholder</Link></article><article className={styles.card}><h2>Email</h2><Link className={styles.button} href="/contact">Contact form shell</Link></article></div><section className={styles.card}><h2>Wholesale FAQ</h2><Accordion items={wholesaleFaq.map(([title,content],index)=>({id:`support-${index}`,title,content:<p>{content}</p>}))} /></section></DealerShell>; }
