// @vitest-environment jsdom
import{render,screen}from"@testing-library/react";import{describe,expect,it}from"vitest";
import Dashboard,{metadata as cmsMetadata}from"@/app/cms/page";import Homepage from"@/app/cms/homepage/page";import Products from"@/app/cms/products/page";import Collections from"@/app/cms/collections/page";import Categories from"@/app/cms/categories/page";import Banners from"@/app/cms/banners/page";import Media from"@/app/cms/media/page";import Blog from"@/app/cms/blog/page";import SEO from"@/app/cms/seo/page";import Theme from"@/app/cms/theme/page";import Navigation from"@/app/cms/navigation/page";import{cmsNavigation,cmsContent}from"@/features/cms";
describe("Phase 3I static CMS",()=>{
it("renders dashboard summary, counters, quick actions and complete navigation",()=>{const{container}=render(<Dashboard/>);expect(container.querySelectorAll("h1")).toHaveLength(1);expect(screen.getByText("7 synthetic drafts")).toBeVisible();expect(screen.getByText("0 live publications")).toBeVisible();const nav=screen.getByRole("navigation",{name:"CMS"});for(const[,label]of cmsNavigation)expect(nav).toHaveTextContent(label);});
it("renders homepage hero and section controls without publication",()=>{render(<Homepage/>);expect(screen.getByLabelText("Hero heading")).toBeVisible();expect(screen.getByLabelText("Primary CTA")).toBeVisible();expect(screen.getByText("Manufacturing story")).toBeVisible();expect(screen.getByRole("button",{name:"Publish placeholder"})).toHaveAttribute("type","button");});
it("renders product editor, gallery and publishing placeholders",()=>{render(<Products/>);expect(screen.getByLabelText("Product name")).toBeVisible();expect(screen.getByRole("img",{name:"Product gallery upload placeholder"})).toBeVisible();expect(screen.getAllByRole("button",{name:"Edit product"})).toHaveLength(cmsContent.products.length);});
it("renders collection and category add/edit/visibility systems",()=>{const first=render(<Collections/>);expect(screen.getByLabelText("Collection name")).toBeVisible();expect(screen.getAllByRole("button",{name:"Edit"})).toHaveLength(cmsContent.collections.length);first.unmount();render(<Categories/>);expect(screen.getByLabelText("Category name")).toBeVisible();expect(screen.getAllByText("Featured / visible placeholder")).toHaveLength(cmsContent.categories.length);});
it("renders all banner preview slots",()=>{render(<Banners/>);expect(screen.getAllByRole("button",{name:"Preview banner"})).toHaveLength(4);expect(screen.getByRole("img",{name:"Dealer banner preview placeholder"})).toBeVisible();});
it("renders searchable media library without uploads",()=>{render(<Media/>);expect(screen.getByLabelText("Search media")).toBeVisible();expect(screen.getByRole("button",{name:"Upload unavailable"})).toBeDisabled();expect(screen.getAllByRole("button",{name:"Preview media"})).toHaveLength(cmsContent.media.length);});
it("renders plain blog editor and SEO fields",()=>{const first=render(<Blog/>);expect(screen.getByLabelText("Article body")).toBeVisible();expect(screen.getAllByText("Draft")).toHaveLength(cmsContent.blogs.length);first.unmount();render(<SEO/>);expect(screen.getByLabelText("Canonical placeholder")).toBeVisible();expect(screen.getByLabelText("Structured data placeholder")).toBeDisabled();});
it("renders theme manager without changing semantic tokens",()=>{render(<Theme/>);expect(screen.getByLabelText("Logo placeholder")).toBeDisabled();expect(screen.getByDisplayValue("Semantic ink token")).toBeVisible();expect(screen.getByRole("button",{name:"Button preview"})).toBeVisible();});
it("renders header, footer and dealer navigation groups",()=>{render(<Navigation/>);for(const heading of["Header menu","Footer menu","Dealer menu"])expect(screen.getByRole("heading",{name:heading})).toBeVisible();});
it("keeps CMS metadata private",()=>{expect(cmsMetadata.robots).toEqual({index:false,follow:false});expect(JSON.stringify(cmsMetadata)).not.toContain("https://");});
});
