import { SITE_CONFIG_VERSION, type SiteConfiguration } from "./types";

const nav = (
  id: string,
  label: string,
  url: string,
  area: "PRIMARY" | "SECONDARY",
  sortOrder: number,
) => ({
  id,
  label,
  url,
  area,
  sortOrder,
  visible: true,
  openInNewTab: false,
  developmentNote: "Development navigation",
  icon: "placeholder",
});
const link = (
  id: string,
  label: string,
  url: string,
  group: "CUSTOMER" | "WHOLESALE" | "COLLECTIONS" | "POLICIES",
) => ({ id, label, url, group });

export const defaultSiteConfiguration: SiteConfiguration = {
  version: SITE_CONFIG_VERSION,
  header: { logoText: "Silver Sankha", logoSubtitle: "Jewellery House" },
  navigation: [
    nav("home", "Home", "/", "PRIMARY", 1),
    nav("products", "Products", "/products", "PRIMARY", 2),
    nav("categories", "Categories", "/products", "PRIMARY", 3),
    nav("collections", "Collections", "/collections", "PRIMARY", 4),
    nav("about", "About", "/about", "PRIMARY", 5),
    nav("contact", "Contact", "/contact", "PRIMARY", 6),
    nav("wholesale", "Wholesale", "/wholesale", "PRIMARY", 7),
    nav("guides", "Guides", "/guides", "SECONDARY", 1),
    nav("blog", "Blog", "/blog", "SECONDARY", 2),
    nav("reviews", "Reviews", "/reviews", "SECONDARY", 3),
    nav("dealer", "Dealer", "/dealer", "SECONDARY", 4),
  ],
  footer: {
    companyName: "Silver Sankha Jewellery House",
    description: "Made with discipline. Shared with warmth.",
    copyright: "Silver Sankha. Public simulation.",
    phone: "+91 00000 00000",
    email: "hello@example.invalid",
    address: "Development address, Kolkata, India",
    whatsappLabel: "WhatsApp preview",
    instagram: "/social/instagram",
    facebook: "/social/facebook",
    youtube: "/social/youtube",
    notice: "Development content — stored only in this browser.",
    links: [
      link("privacy", "Privacy Policy", "/policies/privacy", "POLICIES"),
      link("terms", "Terms", "/policies/terms", "POLICIES"),
      link("returns", "Returns", "/policies/delivery-returns", "POLICIES"),
      link("shipping", "Shipping", "/policies/delivery-returns", "POLICIES"),
      link("care", "Customer care", "/guides", "CUSTOMER"),
      link("contact-footer", "Contact", "/contact", "CUSTOMER"),
      link("wholesale-footer", "Partner with us", "/wholesale", "WHOLESALE"),
      link("dealer-footer", "Dealer portal", "/dealer", "WHOLESALE"),
      link("collections-footer", "Collections", "/collections", "COLLECTIONS"),
      link("products-footer", "Products", "/products", "COLLECTIONS"),
    ],
  },
  announcement: {
    visible: true,
    message: "Development catalogue — simulated content",
    ctaLabel: "Explore products",
    ctaUrl: "/products",
    backgroundToken: "surface-inverse",
    textToken: "text-inverse",
    priority: 1,
    festivalBadge: "",
    dismissible: false,
  },
  seo: {
    homepageTitle: "Silver Sankha Jewellery House",
    homepageDescription: "A development-only premium jewellery storefront.",
    productTitleTemplate: "%s | Silver Sankha",
    categoryTitleTemplate: "%s Jewellery | Silver Sankha",
    collectionTitleTemplate: "%s Collection | Silver Sankha",
    openGraphTitle: "Silver Sankha Jewellery House",
    openGraphDescription: "Development-only public catalogue preview.",
    twitterTitle: "Silver Sankha Jewellery House",
    twitterDescription: "Development-only public catalogue preview.",
    canonicalBaseUrl: "http://localhost:3001",
    robots: "index,follow",
    noindex: false,
    nofollow: false,
  },
};
export const cloneSiteConfiguration = (
  value: SiteConfiguration = defaultSiteConfiguration,
) => structuredClone(value);
